name:                Minesweeper
version:             0.1.0.0
synopsis:            A simple Minesweeper game
description:         This package provides a simple implementation of the Minesweeper game.
category:            Game
author:              Abanoub Razkalla
maintainer:          abanoub.maged171@gmail.com
license:             MIT
license-file:        LICENSE


dependencies:
  - base >=4.7 && <5
  - random
  - tasty
  - tasty-hunit
  - containers


library:
  source-dirs: src

executables:
  Minesweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - Minesweeper
      - random
      - containers



tests:
  Minesweeper-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - Minesweeper
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - random
      - containers
      - silently
